const libs =  {
  name: 'misc',// Do not change this name. It's "reserved"
  items: [
    // <npm-package-name> or [<npm-package-name>, <seo-alias>]
    // Seo aliases are used to refer to npm packages in Google Search results. For example, for 'angular/core' Google will show results with a title "Angular: Stats and Trends - Moiva.io".
    // Aliases are important to help users find the right page
    // Important: when adding an alias, make sure it's unique - no other packages in this file should use it as their name
    [ '@nivo/core', 'plouc/nivo', null, null ],
    [ 'apisauce', 'skellock/apisauce', null, null ],
    [ 'async', 'caolan/async', null, null ],
    [ 'axios', 'axios/axios', null, null ],
    [ 'bluebird', 'petkaantonov/bluebird', null, null ],
    [ 'browserify', 'browserify/browserify', null, null ],
    [ 'buefy', 'buefy/buefy', null, null ],
    [ 'chai', 'chaijs/chai', null, null ],
    [ 'commander', 'tj/commander.js', null, null ],
    [ 'commitizen', 'commitizen/cz-cli', 'Commitizen', null ],
    [ 'classnames', 'JedWatson/classnames', null, null ],
    [ 'cheerio', 'cheeriojs/cheerio', null, null ],
    [ 'core-js', 'zloirock/core-js', null, null ],
    [ 'debug', 'visionmedia/debug', null, null ],

    [ 'fp-ts', 'gcanti/fp-ts', null, null ],
    [ 'grunt', 'gruntjs/grunt', null, null ],
    [ 'gulp', 'gulpjs/gulp', null, null ],
    [ 'inquirer', 'SBoudrias/Inquirer.js', null, null ],
    [ 'jasmine-core', 'jasmine/jasmine', null, null ],
    [ 'jquery', 'jquery/jquery', null, null ],
    [ 'karma', 'karma-runner/karma', null, null ],
    [ 'less', 'less/less.js', null, null ],
    [ 'mkdirp', 'isaacs/node-mkdirp', null, null ],
    [ 'mocha', 'mochajs/mocha', null, null ],
    [ 'node-fetch', 'bitinn/node-fetch', null, null ],
    [ 'passport', 'jaredhanson/passport', null, null ],
    [ 'prop-types', 'facebook/prop-types', null, null ],
    [ 'protractor', 'angular/protractor', null, null ],
    [ 'react-chartjs-2', 'reactchartjs/react-chartjs-2', null, null ],

    [ 'react-router', 'ReactTraining/react-router', null, null ],
    [ 'react-vis', 'uber-common/react-vis', null, null ],
    [ 'sanctuary', 'sanctuary-js/sanctuary', null, null ],
    [ 'sass', 'sass/dart-sass', null, null ],
    [ 'superagent', 'visionmedia/superagent', null, null ],
    [ 'universal-router', 'kriasoft/universal-router', null, null ],
    [ 'uuid', 'uuidjs/uuid', null, null ],
    [ 'victory', 'formidablelabs/victory', null, null ],
    [ 'yargs', 'yargs/yargs', null, null ],
    [ 'postcss', 'postcss/postcss', null, null ],
    [ 'create-react-app', 'facebook/create-react-app', 'Create React App', null ],
    [ 'react-native', 'facebook/react-native', null, null ],
    [ 'electron', 'electron/electron', null, null ],
    [ 'animate.css', 'animate-css/animate.css', null, null ],

    [ '@fortawesome/fontawesome-free', 'FortAwesome/Font-Awesome', 'Font Awesome', null ],
    [ 'reveal.js', 'hakimel/reveal.js', null, null ],
    [ '@ionic/core', 'ionic-team/ionic', 'Ionic', null ],
    [ 'normalize.css', 'necolas/normalize.css', null, null ],
    [ 'material-design-icons', 'google/material-design-icons', 'Material Icons', null ],
    [ 'yarn', 'yarnpkg/yarn', null, null ],
    [ 'serverless', 'serverless/serverless', 'Serverless Framework', null ],
    [ '@babel/core', 'babel/babel', 'Babel', null ],
    [ 'animejs', 'juliangarnier/anime', null, null ],
    [ 'impress.js', 'impress/impress.js', null, null ],
    [ 'ghost', 'TryGhost/Ghost', null, null ],
    [ 'mermaid', 'knsv/mermaid', null, null ],
    [ 'strapi', 'strapi/strapi', null, null ],
    [ 'pixi.js', 'pixijs/pixi.js', 'PixiJS', null ],
    [ 'fullpage.js', 'alvarotrigo/fullPage.js', 'fullPage.js', null ],
    [ '@atomist/hackathon-starter', 'sahat/hackathon-starter', 'Hackathon Starter', null ],
    [ 'video.js', 'videojs/video.js', null, null ],

    [ 'clipboard', 'zenorocha/clipboard.js', 'clipboard.js', null ],
    [ 'faker', 'Marak/Faker.js', 'Faker.js', null ],
    [ 'phaser', 'photonstorm/phaser', null, null ],
    [ 'quill', 'quilljs/quill', null, null ],
    [ 'ant-design-pro', 'ant-design/ant-design-pro', 'Ant Design Pro', null ],
    [ '@vue/cli', 'vuejs/vue-cli', 'Vue CLI', 'vue' ],
    [ 'slick-carousel', 'kenwheeler/slick', 'Slick', null ],
    [ 'lerna', 'lerna/lerna', null, null ],
    [ 'swiper', 'nolimits4web/Swiper', null, null ],
    [ 'request', 'request/request', null, null ],
    [ 'standard', 'standard/standard', 'JavaScript Standard Style', null ],
    [ 'modernizr', 'Modernizr/Modernizr', null, null ],
    [ 'whatwg-fetch', 'github/fetch', 'Fetch', null ],
    [ 'xlsx', 'SheetJS/sheetjs', 'SheetJS js-xlsx', null ],
    [ 'marked', 'markedjs/marked', null, null ],
    [ '@angular/cli', 'angular/angular-cli', 'Angular CLI', 'angular' ],
    [ '@uppy/core', 'transloadit/uppy', 'Uppy', null ],
    [ 'sequelize', 'sequelize/sequelize', null, null ],
    [ 'webtorrent', 'webtorrent/webtorrent', 'WebTorrent', null ],

    [ 'webtorrent-cli', 'webtorrent/webtorrent-cli', null, null ],
    [ 'lottie-web', 'airbnb/lottie-web', 'Lottie for Web', null ],
    [ 'monaco-editor', 'Microsoft/monaco-editor', 'Monaco Editor', null ],
    [ 'tesseract.js', 'naptha/tesseract.js', null, null ],
    [ 'typeorm', 'typeorm/typeorm', 'TypeORM', null ],
    [ '@tabler/core', 'tabler/tabler', 'Tabler', null ],
    [ 'ace-builds', 'ajaxorg/ace-builds', 'Ace', null ],
    [ 'react-beautiful-dnd', 'atlassian/react-beautiful-dnd', null, null ],
    [ 'mongoose', 'Automattic/mongoose', null, null ],
    [ 'hammerjs', 'hammerjs/hammer.js', 'hammer.js', null ],
    [ 'codemirror', 'codemirror/CodeMirror', 'CodeMirror', null ],
    [ 'sortablejs', 'SortableJS/Sortable', 'Sortable', null ],
    [ 'lighthouse', 'GoogleChrome/lighthouse', null, null ],
    [ '@polymer/polymer', 'Polymer/polymer', 'Polymer', null ],
    [ 'polymer-cli', 'Polymer/tools', null, null ],
    [ 'husky', 'typicode/husky', null, null ],
    [ 'purecss', 'pure-css/pure', 'Pure.css', null ],
    [ 'redux-saga', 'redux-saga/redux-saga', null, null ],
    [ 'jspdf', 'MrRio/jsPDF', 'jsPDF', null ],
    [ '@angular/material', 'angular/components', 'Material for Angular', null ],
    [ 'react-virtualized', 'bvaughn/react-virtualized', null, null ],
    [ 'react-window', 'bvaughn/react-window', null, null ],
    [ 'dragula', 'bevacqua/dragula', null, null ],
    [ 'intro.js', 'usablica/intro.js', null, null ],

    [ 'normalizr', 'paularmstrong/normalizr', null, null ],
    [ 'draft-js', 'facebook/draft-js', 'Draft.js', null ],
    [ 'nativescript', 'NativeScript/NativeScript', null, null ],
    [ 'feather-icons', 'feathericons/feather', 'Feather', null ],
    [ 'slate', 'ianstormtaylor/slate', null, null ],
    [ 'scrollreveal', 'jlmakes/scrollreveal', null, null ],
    [ 'react-motion', 'chenglou/react-motion', null, null ],
    [ '@mostly-adequate/support', 'MostlyAdequate/mostly-adequate-guide', 'Guide to FP', null ],
    [ 'react-spring', 'drcmda/react-spring', null, null ],
    [ 'autoprefixer', 'postcss/autoprefixer', null, null ],
    [ 'flv.js', 'Bilibili/flv.js', null, null ],
    [ 'plyr', 'sampotts/plyr', null, null ],
    [ 'sharp', 'lovell/sharp', null, null ],
    [ 'localforage', 'localForage/localForage', 'localForage', null ],
    [ 'react-use', 'streamich/react-use', null, null ],
    [ 'popmotion', 'Popmotion/popmotion', null, null ],
    [ 'react-native-web', 'necolas/react-native-web', 'React Native for Web', null ],
    [ 'fabric', 'fabricjs/fabric.js', 'Fabric.js', null ],
    [ 'highlight.js', 'highlightjs/highlight.js', null, null ],
    [ 'howler', 'goldfire/howler.js', 'Howler.js', null ],
    [ 'vue-router', 'vuejs/vue-router', 'Vue Router', null ],
    [ 'reselect', 'reduxjs/reselect', null, null ],
    [ 'vux', 'airyland/vux', null, null ],
    [ 'pkg', 'zeit/pkg', null, null ],
    [ '@blueprintjs/core', 'palantir/blueprint', 'Blueprint', 'react' ],
    [ 'react-query', 'tannerlinsley/react-query', 'React Query', null ],
    [ 'validator', 'chriso/validator.js', 'validator.js', null ],
    [ 'flux', 'facebook/flux', null, null ],

    [ 'js-cookie', 'js-cookie/js-cookie', 'JavaScript Cookie', null ],
    [ 'ccxt', 'ccxt/ccxt', null, null ],
    [ 'velocity-animate', 'julianshapiro/velocity', 'Velocity', null ],
    [ 'angular-material', 'angular/material', 'Material for AngularJS', 'angularjs'],
    [ 'egg', 'eggjs/egg', null, null ],
    [ '@popperjs/core', 'popperjs/popper-core', 'Popper', null ],
    [ 'uikit', 'uikit/uikit', 'UIkit', null ],
    [ 'vant', 'youzan/vant', null, 'vue' ],
    [ '@mojs/core', 'mojs/mojs', 'mojs', null ],
    [ 'cleave.js', 'nosir/cleave.js', null, null ],
    [ 'mint-ui', 'ElemeFE/mint-ui', 'Mint UI', null ],
    [ 'file-saver', 'eligrey/FileSaver.js', 'FileSaver.js', null ],
    [ 'streamsaver', 'jimmywarting/StreamSaver.js', 'StreamSaver.js', null ],
    [ 'vite', 'vitejs/vite', null, null ],
    [ 'framework7', 'framework7io/framework7', null, null ],
    [ 'trix', 'basecamp/trix', null, null ],
    [ 'chalk', 'chalk/chalk', null, null ],
    [ 'react-admin', 'marmelab/react-admin', null, 'react' ],
    [ 'coffeescript', 'jashkenas/coffeescript', 'CoffeeScript', null ],
    [ 'react-loadable', 'thejameskyle/react-loadable', null, null ],
    [ 'ink', 'vadimdemedes/ink', null, null ],
    [ 'dva', 'dvajs/dva', 'DvaJS', null ],
    [ 'svgo', 'svg/svgo', null, null ],
    [ 'jsdom', 'jsdom/jsdom', null, null ],
    [ 'aos', 'michalsnik/aos', null, null ],
    [ 'swr', 'vercel/swr', 'SWR', null ],
    [ 'ar.js', 'jeromeetienne/AR.js', null, null ],
    [ 'masonry-layout', 'desandro/masonry', null, null ],
    [ 'react-dnd', 'react-dnd/react-dnd', 'React DnD', null ],
    [ 'ionicons', 'ionic-team/ionicons', null, null ],
    [ 'rxdb', 'pubkey/rxdb', 'RxDB', null ],
    [ 'roughjs', 'pshihn/rough', 'Rough.js', null ],
    [ 'medium-editor', 'yabwe/medium-editor', 'MediumEditor', null ],
    [ 'q', 'kriskowal/q', null, null ],

    [ 'zepto', 'madrobby/zepto', 'Zepto.js', null ],
    [ '@shopify/draggable', 'Shopify/draggable', 'Draggable', null ],
    [ 'p5', 'processing/p5.js', null, null ],
    [ 'lazysizes', 'aFarkas/lazysizes', null, null ],
    [ 'handsontable', 'handsontable/handsontable', null, null ],
    [ 'recompose', 'acdlite/recompose', null, 'react' ],
    [ 'lowdb', 'typicode/lowdb', null, null ],
    [ 'native-base', 'GeekyAnts/NativeBase', null, null ],
    [ '@tensorflow/tfjs', 'tensorflow/tfjs', 'TensorFlow.js', null ],
    [ 'xstate', 'davidkpiano/xstate', null, null ],
    [ '@editorjs/editorjs', 'codex-team/editor.js', 'Editor.js', null ],
    [ 'prepack', 'facebook/prepack', null, null ],
    [ 'n', 'tj/n', null, null ],
    [ 'blessed-contrib', 'yaronn/blessed-contrib', null, null ],
    [ 'blessed', 'chjj/blessed', null, null ],
    [ 'weex-vue-render', 'weexteam/weex-vue-render', null, null ],
    [ 'pouchdb', 'pouchdb/pouchdb', 'PouchDB', null ],
    [ '@theia/core', 'eclipse-theia/theia', 'Eclipse Theia', null ],
    [ 'flatpickr', 'chmln/flatpickr', null, null ],
    [ 'frappe-charts', 'frappe/charts', 'Frappe Charts', null ],
    [ 'knex', 'knex/knex', 'knex.js', null ],
    [ 'jsonwebtoken', 'auth0/node-jsonwebtoken', null, null ],
    [ 'vivus', 'maxwellito/vivus', 'vivus.js', null ],
    [ '@fullcalendar/core', 'fullcalendar/fullcalendar', 'FullCalendar', null ],
    [ 'nodemailer', 'nodemailer/nodemailer', null, null ],
    [ 'react-table', 'tannerlinsley/react-table', 'React Table', 'react' ],
    [ 'store', 'marcuswestin/store.js', 'Store.js', null ],
    [ 'netlify-cms-app', 'netlify/netlify-cms', 'Netlify CMS', null ],
    [ 'katex', 'KaTeX/KaTeX', 'KaTeX', null ],
    [ 'snapsvg', 'adobe-webplatform/Snap.svg', 'Snap.svg', null ],
    [ 'dotenv', 'motdotla/dotenv', null, null ],
    [ 'bit-bin', 'teambit/bit', 'Bit', null ],
    [ 'expo-cli', 'expo/expo-cli', null, null ],
    [ 'expo', 'expo/expo', null, null ],
    [ 'react-grid-layout', 'STRML/react-grid-layout', 'React-Grid-Layout', 'react' ],
    [ 'headless-recorder', 'checkly/headless-recorder', 'Headless Recorder', null ],
    [ 'bootswatch', 'thomaspark/bootswatch', null, null ],
    [ 'selectize', 'selectize/selectize.js', 'selectize.js', null ],
    [ 'turbolinks', 'turbolinks/turbolinks', null, null ],
    [ 'gun', 'amark/gun', null, null ],

    [ 'super-tiny-icons', 'edent/SuperTinyIcons', 'Super Tiny Icons', null ],
    [ 'grapesjs', 'artf/grapesjs', 'GrapesJS', null ],
    [ 'sweetalert2', 'sweetalert2/sweetalert2', null, null ],
    [ 'aframe', 'aframevr/aframe', 'A-Frame', null ],
    [ '@toast-ui/editor', 'nhn/tui.editor', 'TOAST UI Editor', null ],
    [ 'react-intl', 'formatjs/formatjs', 'React Intl', null ],
    [ '@vx/vx', 'hshoff/vx', 'visx', null ],
    [ 'paper', 'paperjs/paper.js', 'Paper.js', null ],
    [ 'driver.js', 'kamranahmedse/driver.js', null, null ],
    [ 'twemoji', 'twitter/twemoji', null, null ],
    [ 'n8n', 'n8n-io/n8n', null, null ],
    [ 'johnny-five', 'rwaldron/johnny-five', null, null ],
    [ 'gpu.js', 'gpujs/gpu.js', 'GPU.js', null ],
    [ 'react-native-navigation', 'wix/react-native-navigation', 'React Native Navigation', null ],
    [ 'react-hot-loader', 'gaearon/react-hot-loader', 'React Hot Loader', null ],
    [ 'gsap', 'greensock/GSAP', 'GSAP', null ],
    [ 'fuse.js', 'krisk/Fuse', null, null ],
    [ 'verbal-expressions', 'VerbalExpressions/JSVerbalExpressions', 'JSVerbalExpressions', null ],
    [ 'brain.js', 'brainjs/brain.js', null, null ],
    [ 'omi', 'Tencent/omi', null, null ],
    [ 'react-three-fiber', 'drcmda/react-three-fiber', null, null ],
    [ 'shelljs', 'shelljs/shelljs', 'ShellJS', null ],
    [ 'smartcrop', 'jwagner/smartcrop.js', 'smartcrop.js', null ],
    [ 'mjml', 'mjmlio/mjml', 'MJML', null ],
    [ 'pell', 'jaredreich/pell', null, null ],
    [ 'node-red', 'node-red/node-red', 'Node-RED', null ],
    [ 'co', 'tj/co', null, null ],
    [ 'nanoid', 'ai/nanoid', 'Nano ID', null ],
    [ 'browser-sync', 'BrowserSync/browser-sync', 'Browsersync', null ],
    [ 'systemjs', 'systemjs/systemjs', 'SystemJS', null ],
    [ 'pomelo', 'NetEase/pomelo', null, null ],
    [ 'verdaccio', 'verdaccio/verdaccio', null, null ],
    [ 'matter-js', 'liabru/matter-js', 'Matter.js', null ],
    [ 'redux-persist', 'rt2zz/redux-persist', 'Redux Persist', null ],
    [ 'virtual-dom', 'Matt-Esch/virtual-dom', null, null ],
    [ 'markdown-it', 'markdown-it/markdown-it', null, null ],
    [ 'apollo-server', 'apollographql/apollo-server', 'Apollo Server', null ],
    [ '@assemblyscript/loader', 'AssemblyScript/assemblyscript', 'AssemblyScript', null ],
    [ 'jimp', 'oliver-moran/jimp', null, null ],
    [ 'jquery-ui', 'jquery/jquery-ui', 'jQuery UI', null ],
    [ 'raphael', 'DmitryBaranovskiy/raphael', null, null ],

    [ 'supertest', 'visionmedia/supertest', 'SuperTest', null ],
    [ 'x-data-spreadsheet', 'myliang/x-spreadsheet', 'x-spreadsheet', null ],
    [ 'mathjs', 'josdejong/mathjs', 'Math.js', null ],
    [ 'headroom.js', 'WickyNilliams/headroom.js', null, null ],
    [ 'proton-native', 'kusti8/proton-native', null, null ],
    [ 'dplayer', 'DIYgod/DPlayer', 'DPlayer', null ],
    [ 'tone', 'Tonejs/Tone.js', 'Tone.js', null ],
    [ 'stylus', 'stylus/stylus', null, null ],
    [ 'crypto-js', 'brix/crypto-js', null, null ],
    [ 'mousetrap', 'ccampbell/mousetrap', null, null ],
    [ '@antv/g2', 'antvis/g2', 'G2', null ],
    [ '@antv/g2plot', 'antvis/g2plot', 'G2Plot', null ],
    [ '@swc/core', 'swc-project/swc', 'swc', null ],
    [ 'filepond', 'pqina/filepond', null, null ],
    [ 'react-content-loader', 'danilowoz/react-content-loader', null, 'react' ],
    [ 'list.js', 'javve/list.js', null, null ],
    [ '@mdx-js/mdx', 'mdx-js/mdx', 'MDX', null ],
    [ 'fx', 'antonmedv/fx', null, null ],
    [ '@fluentui/react', 'microsoft/fluentui', 'Fluent UI Web/React', null ],
    [ 'nock', 'nock/nock', null, null ],
    [ 'botkit', 'howdyai/botkit', null, null ],
    [ 'electron-builder', 'electron-userland/electron-builder', null, null ],
    [ 'vue-resource', 'pagekit/vue-resource', null, null ],
    [ 'bull', 'OptimalBits/bull', null, null ],
    [ '@primer/css', 'primer/css', 'Primer CSS', null ],
    [ 'web-vitals', 'GoogleChrome/web-vitals', null, null ],
    [ '@vueuse/core', 'vueuse/vueuse', 'VueUse', null ],
  ]
};

module.exports = libs;
