const libs =  {
  name: 'misc',// Do not change this name. It's "reserved"
  items: [
    // <npm-package-name> or [<npm-package-name>, <seo-alias>]
    // Seo aliases are used to refer to npm packages in Google Search results. For example, for 'angular/core' Google will show results with a title "Angular: Stats and Trends - Moiva.io".
    // Aliases are important to help users find the right page
    // Important: when adding an alias, make sure it's unique - no other packages in this file should use it as their name
    '@cucumber/cucumber',
    '@nivo/core',
    'apisauce',
    'async',
    'axios',
    'bluebird',
    'browserify',
    'buefy',
    'chai',
    'commander',
    'commitizen',
    'classnames',
    'cheerio',
    'core-js',
    'debug',
    'fp-ts',
    'grunt',
    'gulp',
    'inquirer',
    'jasmine',
    'jquery',
    'karma',
    'less',
    'mkdirp',
    'mocha',
    'node-fetch',
    'passport',
    'prop-types',
    'protractor',
    'react-chartjs-2',
    'react-router',
    'react-vis',
    'sanctuary',
    'sass',
    'superagent',
    'universal-router',
    'uuid',
    'victory',
    'yargs',
    ['postcss', 'PostCSS'],
    ['create-react-app', 'Create React App'],
    'react-router-dom',
    'react-native',
    'electron',
    'axios',
    'animate.css',
    'puppeteer',
    ['@fortawesome/fontawesome-free', 'Font Awesome'],
    'reveal.js',
    ['@ionic/core', 'Ionic'],
    'normalize.css',
    ['material-design-icons', 'Material Icons'],
    'yarn',
    ['serverless', 'Serverless Framework'],
    ['@babel/core', 'Babel'],
    'animejs',
    'impress.js',
    'ghost',
    'mermaid',
    'strapi',
    ['pixi.js', 'PixiJS'],
    ['fullpage.js', 'fullPage.js'],
    ['@atomist/hackathon-starter', 'Hackathon Starter'],
    'video.js',
    ['clipboard', 'clipboard.js'],
    ['faker', 'faker.js'],
    'phaser',
    'quill',
    ['ant-design-pro', 'Ant Design Pro'],
    ['@vue/cli', 'Vue CLI', 'vue'],
    ['slick-carousel', 'Slick'],
    'lerna',
    'swiper',
    'request',
    ['standard', 'JavaScript Standard Style'],
    'modernizr',
    ['whatwg-fetch', 'Fetch'],
    ['xlsx', 'SheetJS js-xlsx'],
    'marked',
    ['@angular/cli', 'Angular CLI', 'angular'],
    ['@uppy/core', 'Uppy'],
    'sequelize',
    ['webtorrent', 'WebTorrent'],
    'webtorrent-cli',
    ['lottie-web', 'Lottie for Web'],
    ['monaco-editor', 'Monaco Editor'],
    'tesseract.js',
    ['typeorm', 'TypeORM'],
    ['@tabler/core', 'Tabler'],
    ['ace-builds', 'Ace'],
    'react-beautiful-dnd',
    'mongoose',
    ['hammerjs', 'hammer.js'],
    ['codemirror', 'CodeMirror'],
    ['sortablejs', 'Sortable'],
    'lighthouse',
    ['@polymer/polymer', 'Polymer'],
    'polymer-cli',
    'husky',
    ['purecss', 'Pure.css'],
    'redux-saga',
    ['jspdf', 'jsPDF'],
    ['@angular/material', 'Material for Angular'],
    'react-virtualized',
    'react-window',
    'dragula',
    'intro.js',
    'normalizr',
    ['draft-js', 'Draft.js'],
    'nativescript',
    ['feather-icons', 'Feather'],
    'slate',
    'scrollreveal',
    'react-motion',
    ['@mostly-adequate/support', 'Guide to FP'],
    'react-spring',
    'autoprefixer',
    'flv.js',
    'plyr',
    'sharp',
    ['localforage', 'localForage'],
    'react-use',
    'popmotion',
    ['react-native-web', 'React Native for Web'],
    ['fabric', 'Fabric.js'],
    'highlight.js',
    ['howler', 'Howler.js'],
    ['vue-router', 'Vue Router'],
    'reselect',
    'vux',
    'pkg',
    ['@blueprintjs/core', 'Blueprint', 'react'],
    ['react-query', 'React Query'],
    ['validator', 'validator.js'],
    'flux',
    ['js-cookie', 'JavaScript Cookie'],
    'ccxt',
    ['velocity-animate', 'Velocity']
    ['angular-material', 'Material for AngularJS', 'angularjs'],
    'egg',
    ['@popperjs/core', 'Popper'],
    ['uikit', 'UIkit'],
    ['vant', null, 'vue'],
    ['@mojs/core', 'mojs'],
    'cleave.js',
    ['mint-ui', 'Mint UI'],
    ['file-saver', 'FileSaver.js'],
    ['streamsaver', 'StreamSaver.js'],
    'vite',
    'framework7',
    'trix',
    'chalk',
    ['react-admin', null, 'react'],
    ['coffeescript', 'CoffeeScript'],
    'react-loadable',
    'ink',
    ['dva', 'DvaJS'],
    'svgo',
    'jsdom',
    'aos',
    ['swr', 'SWR'],
    'ar.js',
    'masonry-layout',
    ['react-dnd', 'React DnD'],
    'ionicons',
    ['rxdb', 'RxDB'],
    ['roughjs', 'Rough.js'],
    ['medium-editor', 'MediumEditor'],
    'q',
    ['zepto', 'Zepto.js'],
    ['@shopify/draggable', 'Draggable'],
    'p5',
    'lazysizes',
    'handsontable',
    ['recompose', null, 'react'],
    'lowdb',
    'native-base',
    ['@tensorflow/tfjs', 'TensorFlow.js'],
    'xstate',
    ['@editorjs/editorjs', 'Editor.js'],
    'prepack',
    'n',
    'blessed-contrib',
    'blessed',
  ]
};

module.exports = libs;
